config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/about'
  # root 'home#index'
  root 'friends#index'
end

app/models/application_record.rb
# The base class for all models in the application.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
# Represents a friend in the application.
class Friend < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
  validates :twitter, presence: true, uniqueness: true
  
end

app/models/user.rb
# Represents a user in the application.
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
# The FriendsController handles actions related to managing friends.
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show; end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: 'Not Authorized to Edit This Friend' if @friend.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
  end
end

app/controllers/home_controller.rb
# The HomeController handles the main landing page and related actions.
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# Module to provide utility methods that can be used across the application.
module ApplicationHelper
end

app/helpers/friends_helper.rb
# Module to provide helper methods related to managing friends.
module FriendsHelper
end

app/helpers/home_helper.rb
# Module to provide helper methods related to the home and landing page.
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
  </div>
<br />
  <div class="form-group">
    
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
  <br />
  <div class="form-group">
    
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <br />
  <div class="form-group">
    
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>
  <br />
  <div class="form-group">
    
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>
  <br />
  <div class="form-group">
    
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
<br />
  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= friend.first_name %> <%= friend.last_name %></h1>
  <p class="lead"> <%= friend.email %>   |
  <%= friend.phone %>   |
  <%= friend.twitter %>
  <hr class="my-4">
  
  <div>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %> |
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend, class:"btn btn-secondary" %> |
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<h1>Friends List</h1>

<div id="friends">
<table class="table table-striped table-bordered table-hover">
<thead class="table-dark">
<tr>
<th>Name</th>
<th>Email</th>
<th>Phone</th>
<th>Twitter</th>

<th></th>
</tr>
</thead>
<tbody>
  <% @friends.each do |friend| %>
    <% if friend.user == current_user %>
    <tr id="<%= dom_id friend %>">
    <td><%= link_to friend.first_name + '  ' + friend.last_name, friend, class:"text-decoration-none" %></td>
        
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
       
        
        

        <td><%= button_to "Destroy", friend, method: :delete, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
  <% end %>
</tbody>
</table>
</div>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>
<% else %>
<div class="card">
  <div class="card-header">
  <h2> Welcome to the Friend List Up<h2>
  </div>
  <div class="card-body">
  <h4> You can add Your friends list with their contacts Info</h4>
  <h5 class="text-primary"> to have your friends list please login<h5>
  <%= link_to "Sign In", new_user_session_path, Class:"btn btn-secondary" %>
  </div>
</div>

<% end %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Friend App', root_path, class:"navbar-brand"%>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Add Friend", new_friend_path, Class:"nav-link" %>
        </li>
        
        <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, Class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, Class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, Class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, Class:"nav-link" %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="card">
  <div class="card-header">
  <h2> Welcome to the Friend List Up<h2>
  </div>
  <div class="card-body">
  <p> You can add Your friends list with their contacts Info<p>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show d-flex justify-content-between" role="alert">
  <%= notice %>You should check in on some of those fields below.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BuildLoginPage</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
  <%= render 'home/header' %>
  <div class="container">
  <br />
  <% if notice %>
  <%= render "layouts/alert" %>
  <% end %>
  <%= yield %>
  <div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>